version: '3.8'

networks:
  traefik-ingress:
    external: true
  monitoring-network:
    external: true
  postgres-network:
    external: true
  platform-network:
    driver: overlay
    attachable: true

volumes:
  platform-redis-data:
  rabbitmq-data:

configs:
  platform-redis-config:
    file: ./platform/src/config/datastores/redis.conf
  rabbitmq-config:
    file: ./platform/src/config/datastores/rabbitmq.conf
  sprocket-core-config:
    file: ./platform/src/config/services/core.json
  sprocket-web-config:
    file: ./platform/src/config/services/web.json
  discord-bot-config:
    file: ./platform/src/config/services/discord-bot.json
  elo-service-config:
    file: ./platform/src/config/services/elo-service.json
  image-generation-frontend-config:
    file: ./platform/src/config/services/image-generation-frontend.json
  image-generation-service-config:
    file: ./platform/src/config/services/image-generation-service.json
  matchmaking-service-config:
    file: ./platform/src/config/services/matchmaking-service.json
  notification-service-config:
    file: ./platform/src/config/services/notification-service.json
  replay-parse-service-config:
    file: ./platform/src/config/services/replay-parse-service.json
  server-analytics-service-config:
    file: ./platform/src/config/services/server-analytics-service.json
  submission-service-config:
    file: ./platform/src/config/services/submission-service.json


services:
  # Platform Datastores
  platform-redis:
    image: redislabs/rejson:2.0.7
    command: >
      --requirepass ${PLATFORM_REDIS_PASSWORD}
      --loadmodule /usr/lib/redis/modules/rejson.so
      --loadmodule /usr/lib/redis/modules/redisearch.so
    volumes:
      - platform-redis-data:/data
    networks:
      - platform-network
      - traefik-ingress
    configs:
      - source: platform-redis-config
        target: /usr/local/etc/redis/redis.conf
    deploy:
      placement:
        constraints:
          - node.labels.role == storage
      labels:
        - "traefik.enable=true"
        - "traefik.tcp.routers.platform-redis.rule=HostSNI(`redis.${ENVIRONMENT_SUBDOMAIN}.${HOSTNAME}`)"
        - "traefik.tcp.routers.platform-redis.tls.certresolver=lets-encrypt-tls"
        - "traefik.tcp.services.platform-redis.loadbalancer.server.port=6379"

  rabbitmq:
    image: rabbitmq:3.9.14-management-alpine
    hostname: "{{.Node.Hostname}}"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - platform-network
      - traefik-ingress
    configs:
      - source: rabbitmq-config
        target: /etc/rabbitmq/rabbitmq.conf
    deploy:
      placement:
        constraints:
          - node.labels.role == storage
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rabbitmq-management.rule=Host(`management.rabbitmq.${ENVIRONMENT_SUBDOMAIN}.${HOSTNAME}`)"
        - "traefik.http.routers.rabbitmq-management.entrypoints=websecure"
        - "traefik.http.routers.rabbitmq-management.tls.certresolver=lets-encrypt-tls"
        - "traefik.http.services.rabbitmq-management.loadbalancer.server.port=15672"
        - "traefik.tcp.routers.rabbitmq-amqp.rule=HostSNI(`rabbitmq.${ENVIRONMENT_SUBDOMAIN}.${HOSTNAME}`)"
        - "traefik.tcp.routers.rabbitmq-amqp.tls.certresolver=lets-encrypt-tls"
        - "traefik.tcp.services.rabbitmq-amqp.loadbalancer.server.port=5672"

  # Core Platform Services
  sprocket-core:
    image: asaxplayinghorse/core:${IMAGE_TAG}
    environment:
      ENV: production
      NODE_ENV: production
    networks:
      - platform-network
      - traefik-ingress
      - postgres-network
    configs:
      - source: sprocket-core-config
        target: /app/config/production.json
    secrets:
      - source: jwt-secret
        target: /app/secret/jwtSecret.txt
      - source: s3-secret-key
        target: /app/secret/minio-secret.txt
      - source: s3-access-key
        target: /app/secret/minio-access.txt
      - source: google-client-id
        target: /app/secret/googleClientId.txt
      - source: google-client-secret
        target: /app/secret/googleSecret.txt
      - source: discord-client-secret
        target: /app/secret/discord-secret.txt
      - source: discord-client-id
        target: /app/secret/discord-client.txt
      - source: platform-redis-password
        target: /app/secret/redis-password.txt
      - source: epic-client-id
        target: /app/secret/epic-client.txt
      - source: epic-client-secret
        target: /app/secret/epic-secret.txt
      - source: steam-api-key
        target: /app/secret/steam-key.txt
      - source: postgres-platform-password
        target: /app/secret/db-secret.txt
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sprocket-core.rule=Host(`api.${ENVIRONMENT_SUBDOMAIN}.${HOSTNAME}`)"
        - "traefik.http.routers.sprocket-core.entrypoints=websecure"
        - "traefik.http.routers.sprocket-core.tls.certresolver=lets-encrypt-tls"
        - "traefik.http.services.sprocket-core.loadbalancer.server.port=3001"

  sprocket-web:
    image: asaxplayinghorse/web:${IMAGE_TAG}
    environment:
      ENV: production
      NODE_ENV: production
    networks:
      - traefik-ingress
    configs:
      - source: sprocket-web-config
        target: /app/config/production.json
    secrets:
      - source: chatwoot-hmac-key
        target: /app/secret/chatwoot-hmac-key.txt
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sprocket-web.rule=Host(`${ENVIRONMENT_SUBDOMAIN}.${HOSTNAME}`)"
        - "traefik.http.routers.sprocket-web.entrypoints=websecure"
        - "traefik.http.routers.sprocket-web.tls.certresolver=lets-encrypt-tls"
        - "traefik.http.services.sprocket-web.loadbalancer.server.port=3000"

  discord-bot:
    image: asaxplayinghorse/discord-bot:${IMAGE_TAG}
    networks:
      - platform-network
    configs:
      - source: discord-bot-config
        target: /app/config/production.json
    secrets:
      - source: discord-bot-token
        target: /app/secret/bot-token.txt
      - source: s3-secret-key
        target: /app/secret/minio-secret.txt
      - source: s3-access-key
        target: /app/secret/minio-access.txt
    deploy:
      labels:
        - "traefik.enable=false"

  # Frontend Services
  image-generation-frontend:
    image: asaxplayinghorse/image-generation-frontend:${IMAGE_TAG}
    networks:
      - platform-network
      - traefik-ingress
    configs:
      - source: image-generation-frontend-config
        target: /app/src/config.json
    secrets:
      - source: s3-secret-key
        target: /app/secret/minio-secret.txt
      - source: s3-access-key
        target: /app/secret/minio-access.txt
      - source: postgres-platform-password
        target: /app/secret/db-secret.txt
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.image-generation-frontend.rule=Host(`image-generation.${ENVIRONMENT_SUBDOMAIN}.${HOSTNAME}`)"
        - "traefik.http.routers.image-generation-frontend.entrypoints=websecure"
        - "traefik.http.routers.image-generation-frontend.tls.certresolver=lets-encrypt-tls"
        - "traefik.http.services.image-generation-frontend.loadbalancer.server.port=3000"

  # Microservices
  notification-service:
    image: asaxplayinghorse/notification-service:${IMAGE_TAG}
    networks:
      - platform-network
    configs:
      - source: notification-service-config
        target: /app/config/production.json
    secrets:
      - source: platform-redis-password
        target: /app/secret/redis-password.txt
    deploy:
      labels:
        - "traefik.enable=false"

  image-generation-service:
    image: asaxplayinghorse/image-generation-service:${IMAGE_TAG}
    networks:
      - platform-network
    configs:
      - source: image-generation-service-config
        target: /app/config/production.json
    secrets:
      - source: s3-secret-key
        target: /app/secret/minio-secret.txt
      - source: s3-access-key
        target: /app/secret/minio-access.txt
      - source: postgres-platform-password
        target: /app/secret/db-secret.txt
    deploy:
      labels:
        - "traefik.enable=false"

  server-analytics-service:
    image: asaxplayinghorse/server-analytics-service:${IMAGE_TAG}
    networks:
      - platform-network
      - monitoring-network
    configs:
      - source: server-analytics-service-config
        target: /app/config/production.json
    secrets:
      - source: influx-token
        target: /app/secret/influx-token
    deploy:
      labels:
        - "traefik.enable=false"

  matchmaking-service:
    image: asaxplayinghorse/matchmaking-service:${IMAGE_TAG}
    networks:
      - platform-network
    configs:
      - source: matchmaking-service-config
        target: /app/config/production.json
    secrets:
      - source: platform-redis-password
        target: /app/secret/redis-password.txt
    deploy:
      labels:
        - "traefik.enable=false"

  replay-parse-service:
    image: asaxplayinghorse/replay-parse-service:${IMAGE_TAG}
    environment:
      ENV: production
    networks:
      - platform-network
    configs:
      - source: replay-parse-service-config
        target: /app/config/production.json
    secrets:
      - source: s3-secret-key
        target: /app/secret/s3-secret
      - source: ballchasing-api-token
        target: /app/secret/ballchasing-token
    deploy:
      labels:
        - "traefik.enable=false"

  elo-service:
    image: asaxplayinghorse/elo-service:${IMAGE_TAG}
    environment:
      REDIS_HOST: platform-redis
      REDIS_PORT: "6379"
      REDIS_PREFIX: ${ENVIRONMENT_SUBDOMAIN}
    networks:
      - platform-network
      - traefik-ingress
    configs:
      - source: elo-service-config
        target: /app/config/production.json
    secrets:
      - source: platform-redis-password
        target: /app/secret/redis-password.txt
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.elo-service.rule=Host(`elo.${ENVIRONMENT_SUBDOMAIN}.${HOSTNAME}`)"
        - "traefik.http.routers.elo-service.entrypoints=websecure"
        - "traefik.http.routers.elo-service.tls.certresolver=lets-encrypt-tls"
        - "traefik.http.services.elo-service.loadbalancer.server.port=3000"

  submission-service:
    image: asaxplayinghorse/submission-service:${IMAGE_TAG}
    environment:
      ENV: production
    networks:
      - platform-network
    configs:
      - source: submission-service-config
        target: /app/config/production.json
    secrets:
      - source: s3-secret-key
        target: /app/secret/minio-secret.txt
      - source: s3-access-key
        target: /app/secret/minio-access.txt
      - source: platform-redis-password
        target: /app/secret/redis-password.txt
    deploy:
      labels:
        - "traefik.enable=false"