traefik:
  ingress:
    domain: traefik.noimbrian.cloud
    label: traefik-internal-dashboard
  node_hostname: sov-sandbox

vault:
  ingress:
    domain: vault.noimbrian.cloud
    label: vault
  vault_service_name: vault

timescale:
  ingress:
    domain: db.noimbrian.cloud
    label: timescaledb
  node_hostname: sov-sandbox

minio:
  ingress:
    domain: files.noimbrian.cloud
    label: minio
  console:
    enabled: true
    domain: console.files.noimbrian.cloud
  mount:
    type: bind # bind or volume
    source: /media/hdd1/minio-storage
  node_hostname: sov-sandbox

rabbitmq:
  ingress:
    domain: rmq.noimbrian.cloud
    label: rabbitmq
  console:
    enabled: true
    domain: rmq.noimbrian.cloud
  node_hostname: sov-sandbox

redis:
  ingress:
    domain: redis.noimbrian.cloud
    label: redis
  node_hostname: sov-sandbox

grafana:
  ingress:
    domain: grafana.noimbrian.cloud
    label: grafana
  node_hostname: sov-sandbox
  smtp:
    enabled: true
    from_address: noreply@sprocket.gg
    host: smtp.sendgrid.net
    user: apikey

influx:
  default:
    bucket: sprocket_dev_analytics
    org: sprocket
    username: admin
  node_hostname: sov-sandbox
  ingress:
    domain: influxdb.noimbrian.cloud
    label: influxdb

loki:
  mount:
    type: bind # bind or volume
    source: /media/hdd2/loki
  node_hostname: sov-sandbox
